---
name: Release

concurrency: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - run: jq -r '"::set-output name=version::v" + .version' package.json
        id: package-json

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPMJS_TOKEN }}
          access: public
          check-version: true

      - name: Tag
        if: steps.publish.outputs.type != 'none'
        run: |
          git tag v${{ steps.publish.outputs.version }}
          git push --tags
