---
name: Release

concurrency: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        node-version: ["20", "21", "22", "23", "24"]
        esbuild-version: ["0.20", "0.21", "0.22", "0.23", "0.24", "0.25"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the code

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          standalone: true
          version: 10

      - name: Install esbuild
        run: pnpm add esbuild@${{ matrix.esbuild-version }}

      - name: Build
        run: pnpm build

      - name: Run Tests (CJS)
        run: pnpm test

      - name: Run Tests (ESM)
        run: pnpm test:esm

  publish:
    needs: [tests]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the code

      - run: jq -r '"version=v" + .version' package.json >> $GITHUB_OUTPUT
        id: package-json

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPMJS_TOKEN }}
          access: public
          strategy: upgrade

      - name: Tag
        if: steps.publish.outputs.type != 'none'
        run: |
          git tag v${{ steps.publish.outputs.version }}
          git push --tags
