---
name: Release

concurrency: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - run: jq -r '"::set-output name=version::v" + .version' package.json
        id: package-json

      - uses: actions/github-script@v6
        if: github.ref_type == 'tag' && github.ref_name != steps.package-json.outputs.version
        with:
          script: core.setFailed('The git ref name does not match package.json version')

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPMJS_TOKEN }}
          access: public
